services:
  caddy:
    container_name: caddy
    restart: unless-stopped
    image: caddy:latest
    ports:
      - ${CADDY_HTTP}
      - ${CADDY_HTTPS}
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
  static-web-server:
    container_name: static-web-server
    build:
      dockerfile: ./conf/Containerfile

volumes:
  caddy_data:
  caddy_config:
