services:
  caddy:
    build:
      dockerfile: ./conf/Containerfile
    restart: unless-stopped
    ports:
      - ${CADDY_HTTP}
      - ${CADDY_HTTPS}
    volumes:
      - ./conf:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
