services:

  caddy:
    container_name: caddy-proxy
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "2080:80"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-net

  static-web-server:
    container_name: static-web-server
    restart: unless-stopped
    depends_on:
      - caddy
    build:
      dockerfile: config/server.Containerfile
    ports:
      - "1111:80"
    networks:
      - proxy-net

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy-net:
