services:
  zola:
    build:
      context: .
      dockerfile: ./config/dev.Containerfile
      image: zola
      pull: ghcr.io/getzola/zola:latest
      cache_to: type=local,dest=/public
    command: ["zola", "--config", "config/zola.config.toml", "build"]

  static-web-server:
    build:
      context: .
      dockerfile: ./config/dev.Containerfile
      image: static-web-server
      pull: ghcr.io/static-web-server/static-web-server:2
      cache_from: type=local,src=/public
      volumes:
        - ./config/dev.config.toml:/config.toml
      ports:
        - "8787:80" 
