services:

  caddy:
    env_file: .env
    container_name: caddy
    image: "caddy:latest"
    restart: unless-stopped
    ports:
      - "${DEV_HTTPS_PORT}:443"
      - "${DEV_HTTP_PORT}:80"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-net

  static-web-server:
    env_file: .env
    container_name: static-web-server
    depends_on:
      - caddy
    build:
      dockerfile: Containerfile
    networks:
      - proxy-net

volumes:
  caddy_data:
    external: false
  caddy_config:
    external: false

networks:
  proxy-net:
