services:
  zola:
    container_name: zola
    image: zola:v0.17.1
    env_file: 
      - .env
    build:
      dockerfile: ./config/zola.Containerfile
    volumes:
      - type: bind
        source: ${WEBROOT}/public
        target: /brandont.dev/public
    command: --config config/zola.config.toml build

  static-web-server:
    container_name: static-web-server
    image: static-web-server:2
    env_file: 
      - .env
    build:
      dockerfile: ./config/server.Containerfile
    ports:
      - "1111:80"
    volumes:
      - type: bind
        source: ${WEBROOT}/public
        target: /public
