services:

  caddy:
    env_file: .env
    container_name: caddy-proxy
    build:
      dockerfile: config/caddy.Containerfile
    ports:
      - "2080:80"
      - "2880:443"
    volumes:
      - ./config/Caddyfile:/etc/caddy/Caddyfile:Z
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - proxy-net

  static-web-server:
    env_file: .env
    container_name: static-web-server
    depends_on:
      - caddy
    build:
      dockerfile: config/server.Containerfile
    ports:
      - "1111:80"
      - "8787:443"
    networks:
      - proxy-net

volumes:
  caddy_data:
  caddy_config:

networks:
  proxy-net:
