# The URL the site will be built for
base_url = "https://brandont.dev"
title = "brandont.dev"
description = "Brandon's personal website. Blogs, projects, and more."

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

default_language = "en"

# Generate RSS feed
generate_feed = true
feed_filename="rss.xml"

taxonomies = [
  { name = "tags", render = true },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
external_links_target_blank = true

[search]
include_title = true
include_description = true
include_content = true

[slugify]
taxonomies = "on"
