# The URL the site will be built for
base_url = "https://btp.dev"
title = "btp.dev"
description = "Brandon's personal website. Blogs, projects, and more."
build_search_index = false
default_language = "en"
generate_feeds = true
feed_filenames=["atom.xml", "rss.xml"]
ignored_content = ["*.{sh,txt}", "README.*", "**/content/blog/drafts/*"]

taxonomies = [
  { name = "tags", render = true },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"
external_links_target_blank = true

[slugify]
taxonomies = "on"
